### PR TITLE
Scroll extent calculated wrongly - clean version of PR #89

### PR DESCRIPTION
**Pull request by JulienMaille**

### CODE REVIEW

**Comment by JulienMaille** [comment]
@Pomis would you know how to write a linux/bash script that add the `Patch` lines automatically?

**Comment by Pomis** [comment]
@JulienMaille not really, never done that, but can have a look when I would have enough free time =))

**Comment by SendNukez** [comment]
Should be possible basically the same way as [this](https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/b8841be47d15c4c5f117cd5f47f130277df0b558/.github/workflows/post-release.yaml#L23). That's the line that sets the package.json's version each release. We just have to find `[Patch]` and replace it until we find the end of the file or another `[INI_Header]`. I'll try this later.

**Comment by SendNukez** [comment]
We should be able to make it so that it first checks if the `[Patch]` header exists in the config.
- If not, It will simply append the patch lines to the config.
- If it does exist it will replace the existing `[Patch]` block with the new patch.

However, I'm not really getting far with this. I'm trying to replace the patch block with this: `sed -E 's/\[Patch\](\r?\n([^[\r\n].*)?)*/PATCH/' config-xpui.ini`, but It's only replacing the `[Patch]` header, not the actual body of the patch and I don't quite get why. The RegEx itself is working [(see)](https://regexr.com/68nj4).

**Comment by SendNukez** [comment]
So, putting:
```bash
echo "PATCHING"
PATCH='[Patch]\nxpui.js_find_8008=,(\w+=)32,\nxpui.js_repl_8008=,`\${1}58,'
if cat config-xpui.ini | grep -oP '\[Patch\]'; then
    perl -i -0777 -pe "s/\[Patch\].*?($|(\r*\n){2})/$PATCH\n\n/s" config-xpui.ini
else
    echo -e "\n$PATCH" >> config-xpui.ini
fi
```
after the `echo "COPYING"` part seems to work. But I can't really test it since I'm only on WSL, not an actual linux machine.
The declaration of `$PATCH` is single-line because I couldn't figure out how to store multi-line vars in bash.
Should also probably add an `uninstall.sh` that does the same as `uninstall.ps1` just to be consistent.

**Comment by JulienMaille** [comment]
@Pomis can you test this command line from a bash?
Under Windows I get `grep: -P supports only unibyte and UTF-8 locales`
````bash
echo "PATCHING"
PATCH="[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}58,"
if cat config-xpui.ini | grep -oP '\[Patch\]'; then
    perl -i -0777 -pe "s/\[Patch\].*?($|(\r*\n){2})/$PATCH\n\n/s" config-xpui.ini
else
    echo -e "\n$PATCH" >> config-xpui.ini
fi
```

**Comment by Pomis** [comment]
@JulienMaille Getting 
```PATCHING
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]```

**Comment by JulienMaille** [comment]
@Pomis Can you test the updade bash command and share a snapshot of the console?

**Comment by JulienMaille** [comment]
@SendNukez why removing then adding `dribbblish-dynamic.js` in the install script?
```bash
spicetify config extensions default-dynamic.js- extensions dribbblish-dynamic.js- extensions dribbblish.js- extensions Vibrant.min.js-
spicetify config extensions dribbblish-dynamic.js
```

**Comment by SendNukez** [comment]
> @SendNukez why removing then adding `dribbblish-dynamic.js` in the install script?

Oops, that's a mistake.

**Comment by SendNukez** [comment]
I just realized, shouldn't we apply the patch before running `spicetify apply`? Also in the PowerShell script?

**Pull request merged**
