### PR TITLE
Add option to display the genre of the current playback

### PR DESCRIPTION
**Pull request by Shinyhero36**

### CODE REVIEW

**Comment by JulienMaille** [comment]
How do you see the genre of a song within Spotify?

**Comment by SendNukez** [comment]
I'd change this to be disabled by default since for me, and probably most people having the info be 4 lines is a bit much. Also should probably change the description to say that it's the artist's genres, not the song specifically.

**Comment by Shinyhero36** [comment]
I changed it to disabled by default and edited the description

**Comment by SendNukez** [comment]
Thank you for your contribution.

**Pull request merged**
