### PR TITLE
change colors to be handled inside scss

### PR DESCRIPTION
**Pull request by SendNukez**
This PR changes the way colors are used in the `scss` files.
Now, we can just use `color: spiceColor(text);` which basically translates to `color: var(--spice-text);`.
Or `color: spiceColor(text, 0.5);` which translates to `color: rgba(var(--spice-rgb-text), 0.5);`.

This also generates `color.ini` based on [this](https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/72cfce0070ab24803ab0b425143dcdcf05a7857c/src/styles/Colors.scss#L1-L18) and sets the initial colors as css variables.

The reason for this change is just me being lazy and wanting vs code to auto complete those kinds of variables, as using the `var(--xxx)` doesn't autocomplete because the vars are only set by spicetify / js.

I haven't changed the styles to actually use `spiceColor()` because I'm working on some styles, and don't want to commit this both at the same time, that's why this is a draft. Otherwise this is done

### CODE REVIEW

**Comment by JulienMaille** [comment]
Make sure you delete original color.ini

**Comment by SendNukez** [comment]
I have

**Comment by JulienMaille** [comment]
My bad, couldn't see it from android app. Time to go to bed!

**Comment by SendNukez** [comment]
No problem. You telling me about problems that don't exist is better than you not telling me about problems that do exist.

Good night!

**Pull request merged**
