### PR TITLE
Hide upgrade button, upgrade to premium menu entry and ad placeholder

### PR DESCRIPTION
**Pull request by Daksh777**

### CODE REVIEW

**Comment by WelkinBunbury** [comment]
yes please

**Comment by SendNukez** [comment]
If @JulienMaille is okay with it I could probably add an config option for this.

**Comment by WelkinBunbury** [comment]
> If @JulienMaille is okay with it I could probably add an config option for this.

give the green light @JulienMaille

**Comment by Daksh777** [comment]
> Isn't this against the TOS?

We're technically just hiding those elements but not deleting them entirely from the app so I don't see why it should be against the ToS. Many other themes hide them as well.
Although, I'm now a lawyer so I can't say with 100% certainty that it's against the ToS or not.

**Comment by WelkinBunbury** [comment]
paste this code at the end of the dribblish user.css file

/* Remove upgrade button*/
.main-topBar-UpgradeButton {
display: none
}
/* Remove upgrade to premium button in user menu /
.main-contextMenu-menuItemButton[href="https://www.spotify.com/premium/"] {
display: none
}
/ Remove ad placeholder in main screen */
.main-leaderboardComponent-container {
display: none
}

++ spicetify apply
++The upgrade button should be gone by now.
++Then reinstall blockthespot

**Comment by SendNukez** [comment]
You can use [this](https://gist.github.com/SendNukez/e4f9102a8b62b61bc3e03762579578af) as an extension to the dribbblish theme. 
just copy it into the spicetify extensions folder and run
```
spicetify config extensions dribbblish-no-ads.js
spicetify apply
```

If Julien worries that blocking these elements is against TOS, then this is the best option, since it is not an "official" part of the theme.

**Comment by Daksh777** [comment]
@WelkinBunbury I've sent this PR for the same thing.

@SendNukez That would be pretty good but if it were to break the TOS of Spotify, it would still break it anyway. Also, it seems like extra work for the user to add another extra extension.

**Comment by SendNukez** [comment]
> @SendNukez That would be pretty good but if it were to break the TOS of Spotify, it would still break it anyway. Also, it seems like extra work for the user to add another extra extension.

Yes, it would break TOS, but because the extension is not part of the main theme it shouldn't cause legal issues or whatever.
And if Julien is okay with it I can easily add this to the main theme, but that is not my call.

**Comment by JulienMaille** [comment]
Don't bother creating a separate js file

**Comment by SendNukez** [comment]
So you're okay with including this in the theme?

**Comment by SendNukez** [comment]
Thank you for this PR!

**Pull request merged**
