### PR TITLE
Refactor config code, add top bar options, color scrollbar handles and add option to round sidebar icons

### PR DESCRIPTION
**Pull request by SendNukez**
I started by refactoring the config code to add a few things I wanted to have and it ended up being more than that:
- The config code now allows for selection Submenus (The Submenus are shown in the Main Menu for a ms for some reason, idk why).
- Added Option to add top Bars like all Windows Programs (Replaced `--os-windows-icon-dodge`). There is still an Option to have none / only top Gap.
- Color Scrollbar Handles
- Added Option to make Sidebar Icons rounded. Defaults to off since in my opinion this matches the Theme more.

### CODE REVIEW

**Comment by SendNukez** [comment]
I'll probably change the config again later this week to be more like lyrics plus for example.

**Comment by JulienMaille** [comment]
You can edit this PR and mark it as a draft if it's not ready for testing.

**Comment by SendNukez** [comment]
It's ready, I'm just going to change it to a better System in the Future. The way I implemented it makes it pretty easy to change the Interface of it. Also the Reason for me to even make the Config easier to work with is for People to be able to easily add custom Extensions to this Theme.

**Comment by SendNukez** [comment]
I also just noticed that I forgot to mention that I also changed the Gradient on the Sidebar to be Pseudo-Elements and added a top scroll Gradient. I will probably make the Gradients disappear when scrolled all the way to the Top / Bottom respectively, but I have not found a way to do this yet. Will probably just bundle it with the new Config.

**Comment by JulienMaille** [comment]
Seems like you have big plans for this theme, do you want a maintainer access?

**Comment by SendNukez** [comment]
If you want to give me Maintainer access I'll gladly take it. It's just that I don't usually work with GitHub so I'm afraid I'll break stuff.

**Comment by SendNukez** [comment]
I just noticed that I have to update the readme too, since the Icon dodge doesn't work like that anymore.

**Pull request merged**
