### PR TITLE
README.md update: more accurate patch

### PR DESCRIPTION
**Pull request by Pomis**
I have about 50 playlists, and with current patch the scrollable area was still cropped

### CODE REVIEW

**Comment by SendNukez** [comment]
I'm not familiar with how the patching works. Maybe @JulienMaille knows more. But you also have to change the install scripts to include the change.

**Comment by JulienMaille** [comment]
Why did you close it?

**Comment by Pomis** [comment]
CI job was trying to check out from this repo, though the branch was in my fork, and thus failing

**Comment by JulienMaille** [comment]
Can you explain what the patch does? Why changing that value does fix the scrolling issue? Thanks

**Comment by Pomis** [comment]
Because stock Spotify playlist item height is 32, and in the theme height was increased, and changing this specific value makes calculation of scroll extent area correspondent to the actual height. I don't know exactly how it works, seems like a replacement of value using regex, but with what it has initially in Readme, it clipped several playlists for me

**Comment by JulienMaille** [comment]
> CI job was trying to check out from this repo, though the branch was in my fork, and thus failing

@SendNukez is it a bug with the CI?

**Comment by SendNukez** [comment]
Seems to be a problem with the [checkout action](https://github.com/actions/checkout/issues/455). I'll look into it.

**Pull request closed without merging**
